name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Build and Test Backend:
    runs-on: debian
    defaults:
      run:
        working-directory: ./backend # run only
    steps:
    - uses: actions/checkout@v3

    - name: Move to Backend
      run: cd backend
    
    - name: Install Packages
      run: yarn

    - name: Build
      run: yarn build

    - name: Run Vitest
      run: yarn test

  Build Frontend:
    runs-on: debian
    defaults:
      run:
        working-directory: ./frontend # run only
    steps:
    - uses: actions/checkout@v3

    - name: Move to Frontend
      run: cd frontend
    
    - name: Install Packages
      run: yarn

    - name: Build
      run: yarn build