name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Build and Test Backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend # run only
    steps:
    - uses: actions/checkout@v3
    
    - name: Enable Corepack
      run: corepack enable

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 24  # or your preferred version
        cache: 'yarn'

    - name: Install Packages
      run: yarn

    - name: Build
      run: yarn build

    - name: Run Vitest
      run: yarn test

  Build Frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend # run only
    steps:
    - uses: actions/checkout@v3

    - name: Enable Corepack
      run: corepack enable

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 24  # or your preferred version
        cache: 'yarn'
    
    - name: Install Packages
      run: yarn

    - name: Build
      run: yarn build